{% set name = "openpmd-validator" %}
{% set version = "1.1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/openPMD/openPMD-validator/archive/{{ version }}.tar.gz
  sha256: cc21d39b26a3658334d32f2a7401acd004700d022f23ef9a8f69e21e1f39b6d7
  patches:
    # remove checked-in meta.yaml file
    - rm-meta.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python >=3.7
    - setuptools
  run:
    - h5py
    - {{ pin_compatible('numpy') }}
    - python >=3.7
    - python-dateutil

test:
  imports:
    - openpmd_validator

about:
  home: https://www.openPMD.org
  license: ISC
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Validator and example scripts for openPMD files"

  description: |
    This repository contains scripts to validate existing files that
    implement the openPMD standard.
    Additional scripts to create random/empty files with the valid markup of
    the standard are also provided.
  dev_url: https://github.com/openPMD/openPMD-validator

extra:
  recipe-maintainers:
    - ax3l
    - RemiLehe
