{% set name = "openpmd-validator" %}
{% set version = "1.1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/openPMD/openPMD-validator/archive/{{ version }}.tar.gz
  sha256: a15153c95350e713866ff44a307548f575bd4a7833b082d65fe2d5d0551d48f8
  patches:
    # remove checked-in meta.yaml file
    - rm-meta.patch

build:
  number: 3
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - h5py
    - {{ pin_compatible('numpy') }}
    - python >={{ python_min }}
    - python-dateutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - openpmd_validator

about:
  home: https://www.openPMD.org
  license: ISC
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Validator and example scripts for openPMD files"

  description: |
    This repository contains scripts to validate existing files that
    implement the openPMD standard.
    Additional scripts to create random/empty files with the valid markup of
    the standard are also provided.
  dev_url: https://github.com/openPMD/openPMD-validator

extra:
  recipe-maintainers:
    - ax3l
    - RemiLehe
